apiVersion: v1
data:
  ClusterConfiguration: |
    apiServer:
      certSANs:
      - 10.0.0.10
      extraArgs:
        authorization-mode: Node,RBAC
      timeoutForControlPlane: 4m0s
    apiVersion: kubeadm.k8s.io/v1beta3
    certificatesDir: /etc/kubernetes/pki
    clusterName: kubernetes
    controllerManager: {}
    dns: {}
    etcd:
      local:
        dataDir: /var/lib/etcd
    imageRepository: k8s.gcr.io
    kind: ClusterConfiguration
    kubernetesVersion: v1.22.9
    networking:
      dnsDomain: cluster.local
      podSubnet: 192.168.0.0/16
      serviceSubnet: 10.96.0.0/12
    scheduler: {}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-05-20T02:17:40Z"
  name: kubeadm-config
  namespace: kube-system
  resourceVersion: "211"
  uid: 33c7806d-fa56-4b03-a7a2-1a3a4d8ea7b1
