apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-05-20T02:17:43Z"
  name: deployment-controller
  namespace: kube-system
  resourceVersion: "323"
  uid: 373e7a86-7242-4073-bc00-e5037f1758af
secrets:
- name: deployment-controller-token-fzvck
